### ISSUE TITLE
De-shift the code

### ISSUE THREAD

**Issue by ghost** [watercolor-games/the-peacenet#1]
This issue is a revival of the pull request back on GitLab that removes a ton of name references to ShiftOS from the code and file structure. Might as well put it on the todo list.

**Comment by 143mailliw** [comment]
I'll start seeing how possible this is.

**Comment by ghost** [comment]
Shouldn't be too hard, de-shifting the filestructure etc should be pretty easy. I'll handle theming.

**Comment by ghost** [comment]
Issue completed by @ComputeLinux .
