### ISSUE TITLE
Seperate the Peace Engine from the Peacenet

### ISSUE THREAD

**Issue by 143mailliw** [watercolor-games/the-peacenet#10]
The Peace Engine seems heavily tied to the Peacenet, which in the long term is a bad idea. I propose having them be two different projects.

**Comment by ghost** [comment]
If you can teach me how to properly do `git submodule`s then I'll set that up. The engine itself is almost entirely untied from the game, just needs to have the theming system redone a bit. See #6 and #1 for what needs to be done before I can do anything like this.

**Comment by ghost** [comment]
All done :)

Peace Engine is now a git submodule. When you clone the Peacenet, add the `--recurse-submodules` command-line option to `git clone`. If you're updating an existing local repo, simply `git pull` like usual, then for the first time you pull in the commit with the submodule info in it, do this:

```bash
git submodule init
git submodule update
```

That'll pull in the engine's code into a directory named `peace-engine` inside the game's repo. Git will treat that subdirectory as its own repo, so you can make changes to the engine right from there and push to the engine's repository at https://github.com/watercolor-games/peace-engine. Once you're ready to update Peacenet itself to the new engine code, go back into your Peacenet repo's root directory, run `git submodule update --remote` just to make sure Git knows of the new changes to the engine, then `git add *`, `git commit -m "Update the engine code"`, and `git push`.

Other people will have to `git pull` like usual, then `git submodule update` to get the new engine code.
