### ISSUE TITLE
Enhance Peacegate Desktop

### ISSUE THREAD

**Issue by ghost** [watercolor-games/the-peacenet#11]
Peacegate Desktop is a bit lackluster right now. It works, but not well. Here are a few things we could do to make it both work and run better.

 - [x] Add a "WriteOperation" event to `FSManager` that triggers when a directory is created or deleted, or a file is written to or deleted. This will allow us to refresh the Desktop Icons when something writes to the FS, instead of refreshing every 10 seconds.
 - [x] Move **System Settings** from the App List in Peacegate Menu to a button next to "Exit Peacegate".
 - [x] Add a better Notifications Panel next to the time.
 - [x] Make the "Show Desktop" button actually _work._
 - [x] Add the ability to create, delete, copy and move folders, files, etc on the desktop as well as Change Desktop Background through a right-click menu.
 - [x] Re-theme Panel Buttons to look better.

Related issues: #9

**Comment by ghost** [comment]
DAMNIT @NetwideRogue YOU BEAT ME TO TICKING THE "Add 'Show Desktop'" CHECKBOX D:

**Comment by DeclanHoare** [comment]
trolled...

**Comment by ghost** [comment]
Just rethemed the panel buttons. Desktop's starting to look nice.

**Comment by ghost** [comment]
You can't copy or move anything, but you can still delete files/folders, create new folders, and change the wallpaper by right-clicking the Desktop.
