### ISSUE TITLE
Anders Jensen's been smokin' the greener grass.

### ISSUE THREAD

**Issue by ghost** [watercolor-games/the-peacenet#25]
In the Credits, the Greener Grass track is incredibly clippy and derpy and...slower than usual. Almost like Anders has that good high, maaaan. Or maybe it's just a Peace Engine bug.

Related issue: https://github.com/watercolor-games/peace-engine/issues/7

**Comment by logantgt** [comment]
Nah, Anders knows what's up

**Comment by ghost** [comment]
Yeaaaaaahhhhhhhh boiiiiiiiiiiiiiiiiiiiiiiii

**Comment by ghost** [comment]
I guess somehow Anders found his way into Skrillex's studio... https://www.youtube.com/watch?v=1RyQRsZibDo&feature=youtu.be

Anyway, the bug's fixed now. :D
